export const COLOR = {
  primary: '#41cff2',
  secondary: '#8ECAE6',
  secondary50: '#8ECAE650',
  third: '#FFB703',
  forth: '#023047',
  fifth: '#219EBC',
  sixth: '#dbf4ff',
  seventh: '#FCE0D3',
  eighth: '#F26A2B',

  background: '#ffffff',
  grayBackGround: '#F4F4F4',
  bgHeader: '#c9eeff',

  main: '#ffffff',

  focus: '#41cff2',
  notFocus: '#000000',
  // ============| Button |=============
  bgButton: '#41cff2',
  borderButton: '#41cff2',
  titleButton: '#ffffff',
  titleButton2: '#41cff2',

  borderColor: '#787878',
  borderColor2: '#9E9898',
  borderColor3: '#E4E4E4',
  placeholder: '#595959',
  placeholder10: '#59595933',

  text: '#000000',
  title: '#023047',
  text2: '#595959',
  textWarn: '#FF0303',

  // find color : https://colorhunt.co
  white: '#ffffff',
  black: '#000000',
  red: '#cc0000',
  redOrange: '#ff3300',
  blue: '#003399',

  gray: '#F6F6F6',
  blueHeader: '#d9f3ff',
  blueHeader2: '#c4ecff',
  blueViolet: '#000066',
  yellow: '#ffff00',
  green: '#339900',
  violet: '#660066',
  orange: '#ff6600',
  lightBlue: '#8ce0f5',
  lightYellow: '#FFEEDB',
  lightGreen: '#D8F2E1',
  exit: '#F25F57',
  warn: '#fce7e6'
};

export const ICON = {
  Home: require('../assets/icon/ic_home.png'),
  Notification: require('../assets/icon/ic_notification.png'),
  Trip: require('../assets/icon/ic_car.png'),
  Support: require('../assets/icon/ic_message.png'),
  Profile: require('../assets/icon/ic_user.png'),
  HomeFocus: require('../assets/icon/ic_home_focus.png'),
  NotificationFocus: require('../assets/icon/ic_notification_focus.png'),
  TripFocus: require('../assets/icon/ic_car_focus.png'),
  SupportFocus: require('../assets/icon/ic_message_focus.png'),
  ProfileFocus: require('../assets/icon/ic_user_focus.png'),
  SteeringWheel: require('../assets/icon/ic_steering_wheel.png'),
  Exit: require('../assets/icon/ic_exit.png'),
  Back: require('../assets/icon/ic_left.png'),
  Next: require('../assets/icon/ic_right.png'),
  Edit: require('../assets/icon/ic_edit.png'),
  Warning: require('../assets/icon/ic_warning.png'),
  Check: require('../assets/icon/ic_check.png'),
  Close: require('../assets/icon/ic_close.png'),
  Camera: require('../assets/icon/ic_camera.png'),
  Heart: require('../assets/icon/ic_heart.png'),
  Location: require('../assets/icon/ic_location.png'),
  Share: require('../assets/icon/ic_share.png'),
  Key: require('../assets/icon/ic_key.png'),
  Company: require('../assets/icon/ic_company.png'),
  Other: require('../assets/icon/ic_bookmark.png'),
  Address: require('../assets/icon/ic_address.png'),
  Card: require('../assets/icon/ic_card.png'),
  Wallet: require('../assets/icon/ic_wallet.png'),
  Add: require('../assets/icon/ic_add.png'),
  MasterCard: require('../assets/image/guide/img_mastercard.png'),
  Tech: require('../assets/image/guide/img_tech.png'),
  Copy: require('../assets/icon/ic_copy.png'),
  Send: require('../assets/icon/ic_send.png'),
  Delete: require('../assets/icon/ic_delete.png'),
  Gift: require('../assets/icon/ic_gift.png'),
  DropDown: require('../assets/icon/ic_down.png'),
  Picture: require('../assets/icon/ic_picture.png'),
  Star: require('../assets/icon/ic_star.png'),
  UnStar: require('../assets/icon/icon-unstar.png'),
  Calendar: require('../assets/icon/ic_calendar.png'),
  Ban: require('../assets/icon/ic_ban.png'),

  License: require('../assets/image/img_license.png'),
  Poster: require('../assets/image/poster.jpg'),
  Done: require('../assets/icon/ic_done.png'),
};
